import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

import { Footer, Layout, Navbar, ThemeSwitch } from "nextra-theme-blog";
import "nextra-theme-blog/style.css";
import { Head, Search } from "nextra/components";
import { getPageMap } from "nextra/page-map";

// Initialize Open Sans font with italic weight
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  style: ["normal", "italic"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={openSans.className}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>
        <Layout>
          <Navbar pageMap={await getPageMap()}>
            <Search />
          </Navbar>

          {children}

          <Footer>
            <footer className="footer footer-horizontal flex w-full items-center justify-between">
              <ThemeSwitch />
              <span
                // style={{ fontFamily: "var(--font-open-sans), sans-serif" }}
                className="font-sans italic">
                freedom Copyright © 2025 Jiwon Jason Choi
              </span>{" "}
            </footer>
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
